apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-angular
  namespace: arc
spec:
  replicas: 3
  template:
    spec:
      repository: CMelerom/spring-petclinic-angular
      labels:
        - helm-gh-runner