name: Reusable CI Workflow
on: workflow_call

jobs:
  test:
    runs-on: helm-gh-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name : Install Dependencies
        run: npm ci